/**
 * Icon Component
 *
 * Maps Font Awesome icon class names to Lucide React components.
 * Accepts FA format ('fas fa-chart-line') or short names ('chart-line').
 * Used by nav systems that store icon identifiers as strings.
 */

import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BookUser,
  Bot,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  Clock,
  CloudUpload,
  Columns3,
  CreditCard,
  DollarSign,
  Download,
  ExternalLink,
  Eye,
  FileText,
  Filter,
  Flag,
  Gauge,
  GraduationCap,
  HelpCircle,
  Inbox,
  Info,
  Landmark,
  Link2,
  ListChecks,
  Loader2,
  Lock,
  Mail,
  MailOpen,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  MessageSquareOff,
  Moon,
  MoreVertical,
  Package,
  PawPrint,
  Phone,
  PieChart,
  Plug,
  Plus,
  Radio,
  RefreshCw,
  RotateCw,
  Scale,
  Search,
  Send,
  Settings,
  Star,
  Stethoscope,
  Sun,
  Table2,
  Tag,
  Trash2,
  TrendingUp,
  Trophy,
  LayoutGrid,
  Undo2,
  User,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Wallet,
  Wifi,
  X,
  Sprout,
  Award,
  ShieldCheck,
  Crown,
  Pause,
  Play,
  XCircle,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  'address-book': BookUser,
  'arrow-left': ArrowLeft,
  'arrow-trend-up': TrendingUp,
  'ban': Ban,
  'bars': Menu,
  'bell': Bell,
  'box-open': Package,
  'briefcase': Briefcase,
  'building-columns': Landmark,
  'calendar': Calendar,
  'calendar-alt': Calendar,
  'calendar-check': CalendarCheck,
  'calendar-day': CalendarDays,
  'chart-bar': BarChart3,
  'chart-line': TrendingUp,
  'chart-pie': PieChart,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle': Circle,
  'circle-notch': Loader2,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'cloud-upload-alt': CloudUpload,
  'cog': Settings,
  'columns': Columns3,
  'comment': MessageCircle,
  'comment-slash': MessageSquareOff,
  'comments': MessageSquare,
  'credit-card': CreditCard,
  'download': Download,
  'ellipsis-v': MoreVertical,
  'envelope': Mail,
  'envelope-open-text': MailOpen,
  'exchange-alt': ArrowLeftRight,
  'exclamation-circle': AlertCircle,
  'exclamation-triangle': AlertTriangle,
  'external-link-alt': ExternalLink,
  'eye': Eye,
  'file-alt': FileText,
  'file-lines': FileText,
  'filter': Filter,
  'flag': Flag,
  'graduation-cap': GraduationCap,
  'inbox': Inbox,
  'info-circle': Info,
  'link': Link2,
  'list-check': ListChecks,
  'lock': Lock,
  'map-marker-alt': MapPin,
  'money-bill-wave': Banknote,
  'moon': Moon,
  'paper-plane': Send,
  'paw': PawPrint,
  'phone': Phone,
  'plug': Plug,
  'plus': Plus,
  'question-circle': HelpCircle,
  'ranking-star': Trophy,
  'redo': RefreshCw,
  'sync': RefreshCw,
  'robot': Bot,
  'rotate-right': RotateCw,
  'dollar-sign': DollarSign,
  'sack-dollar': DollarSign,
  'satellite-dish': Radio,
  'scale-balanced': Scale,
  'search': Search,
  'star': Star,
  'stethoscope': Stethoscope,
  'sun': Sun,
  'table-cells': Table2,
  'tachometer-alt': Gauge,
  'tag': Tag,
  'th-large': LayoutGrid,
  'times': X,
  'times-circle': XCircle,
  'trash-alt': Trash2,
  'triangle-exclamation': AlertTriangle,
  'undo': Undo2,
  'user': User,
  'user-check': UserCheck,
  'user-friends': Users,
  'user-plus': UserPlus,
  'user-slash': UserX,
  'users': Users,
  'wallet': Wallet,
  'wifi': Wifi,
  'seedling': Sprout,
  'certificate': Award,
  'shield-check': ShieldCheck,
  'crown': Crown,
  'pause': Pause,
  'play': Play,
};

export interface IconProps extends React.SVGAttributes<SVGSVGElement> {
  /** FA class name ('fas fa-chart-line') or short name ('chart-line') */
  name: string;
  /** Size in pixels — sets both width and height. Default 16. */
  size?: number;
}

/**
 * Render a Lucide icon from a Font Awesome class name or short name.
 * Falls back to null for unmapped icons.
 */
export function Icon({ name, size = 16, className, ...props }: IconProps) {
  // Strip FA prefix: 'fas fa-chart-line' → 'chart-line'
  const shortName = name.replace(/^(fas|far|fab)\s+fa-/, '');
  const LucideIcon = iconMap[shortName];
  if (!LucideIcon) return null;
  return <LucideIcon className={className} width={size} height={size} {...props} />;
}

export { iconMap };
export type { LucideIcon };
